import Head from 'next/head'
import { PlayIcon } from '@heroicons/react/outline'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Animal Crossing Radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen flex flex-col items-center justify-center'>
        <h1 className='text-lg font-bold'>
          animal crossing radio
        </h1>

        <p>
          <PlayIcon role='button' className='h-8 w-8' />
        </p>
      </main>
    </div>
  )
}
