import Head from 'next/head'
import { Player } from '@components/Player'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Animal Crossing Radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex flex-col items-center justify-center'>
        <Player />
      </main>
    </div>
  )
}
